CREATE DATABASE IF NOT EXISTS lab_buoi_4_5 CHARACTER SET utf8mb4;
USE lab_buoi_4_5;
CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);
